runtime: go111

basic_scaling:
  max_instances: 1

handlers:
- url: /_(config|saveconfig)
  secure: always
  login: admin
  script: auto

- url: /_.*
  secure: always
  login: required
  script: auto

- url: /.*
  secure: optional
  script: auto
